#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProEventsApp.Resource", IsApplication=true)]

namespace ProEventsApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::ProEventsApp.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::ProEventsApp.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::ProEventsApp.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::ProEventsApp.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::ProEventsApp.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::ProEventsApp.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::ProEventsApp.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::ProEventsApp.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::ProEventsApp.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::ProEventsApp.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_right = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int county = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btnSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int connections = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int create = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int events = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int home = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_arrow_back = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int btnDialogSignin = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int btnDialogSignup = 2131230725;
			
			// aapt resource value: 0x7f080018
			public const int btnSave = 2131230744;
			
			// aapt resource value: 0x7f080007
			public const int btnSignIn = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int btnSignUp = 2131230729;
			
			// aapt resource value: 0x7f080010
			public const int connections = 2131230736;
			
			// aapt resource value: 0x7f080016
			public const int county = 2131230742;
			
			// aapt resource value: 0x7f08000e
			public const int createEvents = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int events = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int home = 2131230730;
			
			// aapt resource value: 0x7f080012
			public const int textRegister = 2131230738;
			
			// aapt resource value: 0x7f080004
			public const int txtConfirmPassword = 2131230724;
			
			// aapt resource value: 0x7f080011
			public const int txtConnections = 2131230737;
			
			// aapt resource value: 0x7f080006
			public const int txtCreateAccount = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int txtCreateEvents = 2131230735;
			
			// aapt resource value: 0x7f080017
			public const int txtDescripton = 2131230743;
			
			// aapt resource value: 0x7f08000d
			public const int txtEvents = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int txtFirstName = 2131230739;
			
			// aapt resource value: 0x7f08000b
			public const int txtHome = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int txtOr = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int txtPassword = 2131230722;
			
			// aapt resource value: 0x7f080015
			public const int txtProfession = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int txtSecondName = 2131230740;
			
			// aapt resource value: 0x7f080001
			public const int txtUsername = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int webview = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Create_Event_Form = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dialog_Sign_In = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Dialog_Sign_Up = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main_Profile = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Profile_Set_Up = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int county_prompt = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
